on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
        id: go

      - name: run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --parallelism=2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
